# Generated by Django 2.0 on 2018-06-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasure',
            name='image',
        ),
    ]
