# Generated by Django 2.0 on 2018-06-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0002_remove_treasure_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treasure',
            options={'permissions': (('view_treasure', 'Can see available treasure'), ('change_treasure_status', 'Can change the name of treasure'), ('close_treasure', 'Can remove a treasure by setting its status as closed'))},
        ),
    ]
