# Generated by Django 2.0 on 2018-06-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0004_auto_20180630_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='treasure_image'),
        ),
    ]
